[project]
name = "pholus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "plotnine>=0.15.3",
    "scikit-learn>=1.8.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.2",
    "ty>=0.0.17",
]
